version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: hackaton_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: hackaton
      POSTGRES_USER: devfloydbr
      POSTGRES_PASSWORD: devfloydbr
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    networks:
      - backend

  ws-client:
    image: amritb/socketio-client-tool:latest
    restart: always
    container_name: hackaton_ws
    ports:
      - '8080:8080'
    networks:
      - backend

  node-red:
    image: nodered/node-red
    restart: always
    container_name: hackaton_node-red
    ports:
      - '1880:1880'
    volumes:
      - ./.docker/node-red/data:/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
